//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.DeviceMetering;


namespace Integration.DeviceMeteringService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering-service/", ConfigurationName="DeviceMeteringPortTypes")]
    public interface DeviceMeteringPortTypes
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией importMeteringDeviceValues не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importMeteringDeviceValues", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importMeteringDeviceValues", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExportElectricMeteringValueKindType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExportOneRateMeteringValueKindType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        importMeteringDeviceValuesResponseMessage importMeteringDeviceValues(importMeteringDeviceValuesRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией exportMeteringDeviceHistory не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportMeteringDeviceHistory", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportMeteringDeviceHistory", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExportElectricMeteringValueKindType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ExportOneRateMeteringValueKindType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        exportMeteringDeviceHistoryResponseMessage exportMeteringDeviceHistory(exportMeteringDeviceHistoryRequestMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importMeteringDeviceValuesRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importMeteringDeviceValuesRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/", Order=0)]
        public importMeteringDeviceValuesRequest importMeteringDeviceValuesRequest1;
        
        public importMeteringDeviceValuesRequestMessage()
        {
        }
        
        public importMeteringDeviceValuesRequestMessage(RequestHeader RequestHeader, importMeteringDeviceValuesRequest importMeteringDeviceValuesRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importMeteringDeviceValuesRequest1 = importMeteringDeviceValuesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importMeteringDeviceValuesResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ImportResult ImportResult;
        
        public importMeteringDeviceValuesResponseMessage()
        {
        }
        
        public importMeteringDeviceValuesResponseMessage(ResultHeader ResultHeader, ImportResult ImportResult)
        {
            this.ResultHeader = ResultHeader;
            this.ImportResult = ImportResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportMeteringDeviceHistoryRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exportMeteringDeviceHistoryRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/", Order=0)]
        public exportMeteringDeviceHistoryRequest exportMeteringDeviceHistoryRequest1;
        
        public exportMeteringDeviceHistoryRequestMessage()
        {
        }
        
        public exportMeteringDeviceHistoryRequestMessage(RequestHeader RequestHeader, exportMeteringDeviceHistoryRequest exportMeteringDeviceHistoryRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.exportMeteringDeviceHistoryRequest1 = exportMeteringDeviceHistoryRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportMeteringDeviceHistoryResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/", Order=0)]
        public exportMeteringDeviceHistoryResult exportMeteringDeviceHistoryResult;
        
        public exportMeteringDeviceHistoryResponseMessage()
        {
        }
        
        public exportMeteringDeviceHistoryResponseMessage(ResultHeader ResultHeader, exportMeteringDeviceHistoryResult exportMeteringDeviceHistoryResult)
        {
            this.ResultHeader = ResultHeader;
            this.exportMeteringDeviceHistoryResult = exportMeteringDeviceHistoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DeviceMeteringPortTypesChannel : DeviceMeteringPortTypes, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public class DeviceMeteringPortTypesClient : System.ServiceModel.ClientBase<DeviceMeteringPortTypes>, DeviceMeteringPortTypes
    {
        
        public DeviceMeteringPortTypesClient()
        {
        }
        
        public DeviceMeteringPortTypesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DeviceMeteringPortTypesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DeviceMeteringPortTypesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DeviceMeteringPortTypesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importMeteringDeviceValuesResponseMessage DeviceMeteringPortTypes.importMeteringDeviceValues(importMeteringDeviceValuesRequestMessage request)
        {
            return base.Channel.importMeteringDeviceValues(request);
        }
        
        public ResultHeader importMeteringDeviceValues(RequestHeader RequestHeader, importMeteringDeviceValuesRequest importMeteringDeviceValuesRequest1, out ImportResult ImportResult)
        {
            importMeteringDeviceValuesRequestMessage inValue = new importMeteringDeviceValuesRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importMeteringDeviceValuesRequest1 = importMeteringDeviceValuesRequest1;
            importMeteringDeviceValuesResponseMessage retVal = ((DeviceMeteringPortTypes)(this)).importMeteringDeviceValues(inValue);
            ImportResult = retVal.ImportResult;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        exportMeteringDeviceHistoryResponseMessage DeviceMeteringPortTypes.exportMeteringDeviceHistory(exportMeteringDeviceHistoryRequestMessage request)
        {
            return base.Channel.exportMeteringDeviceHistory(request);
        }
        
        public ResultHeader exportMeteringDeviceHistory(RequestHeader RequestHeader, exportMeteringDeviceHistoryRequest exportMeteringDeviceHistoryRequest1, out exportMeteringDeviceHistoryResult exportMeteringDeviceHistoryResult)
        {
            exportMeteringDeviceHistoryRequestMessage inValue = new exportMeteringDeviceHistoryRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.exportMeteringDeviceHistoryRequest1 = exportMeteringDeviceHistoryRequest1;
            exportMeteringDeviceHistoryResponseMessage retVal = ((DeviceMeteringPortTypes)(this)).exportMeteringDeviceHistory(inValue);
            exportMeteringDeviceHistoryResult = retVal.exportMeteringDeviceHistoryResult;
            return retVal.ResultHeader;
        }
    }
}
