//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;


namespace Integration.Fas
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class getStateResult : BaseAsyncResponseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ImportResult", typeof(CommonResultType), Order=1)]
        public CommonResultType ImportResult
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class importRSORequest : BaseType
    {
        
        public importRSORequest()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RSO", Order=0)]
        public importRSORequestRSO[] RSO
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class importRSORequestRSO
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime ActualDate
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RSOActualDATA", typeof(importRSORequestRSORSOActualDATA), Order=2)]
        public importRSORequestRSORSOActualDATA RSOActualDATA
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RemoveRSO", typeof(importRSORequestRSORemoveRSO), Order=3)]
        public importRSORequestRSORemoveRSO RemoveRSO
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class importRSORequestRSORSOActualDATA
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=0)]
        public string INN
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=1)]
        public string KPP
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Name
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsEntpr
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OGRN", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=4)]
        public string OGRN
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OGRNIP", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=5)]
        public string OGRNIP
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Resource", Order=6)]
        public importRSORequestRSORSOActualDATAResource[] Resource
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public importRSORequestRSORSOActualDATARegistryOfNaturalMonopolies RegistryOfNaturalMonopolies
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public importRSORequestRSORSOActualDATARegistryGuaranteeingSuppliers RegistryGuaranteeingSuppliers
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class importRSORequestRSORSOActualDATAResource
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ResourseType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OKTMO", Order=1)]
        public OKTMORefType[] OKTMO
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class importRSORequestRSORSOActualDATARegistryOfNaturalMonopolies
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime Date
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class importRSORequestRSORSOActualDATARegistryGuaranteeingSuppliers
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Number
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime Date
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/fas/")]
    public class importRSORequestRSORemoveRSO
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=0)]
        public string INN
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=1)]
        public string KPP
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OGRN", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=2)]
        public string OGRN
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OGRNIP", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=3)]
        public string OGRNIP
        {
            get;
            set;
        }
    }
}
