//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.NsiBase;


namespace Integration.Infrastructure
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class exportOKIResultType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OKIGuid
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodeOKI
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public exportOKIResultTypeOKI OKI
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class exportOKIResultTypeOKI : InfrastructureType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class InfrastructureType
    {
        
        public InfrastructureType()
        {
            this.IndependentSource = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public nsiRef Base
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AttachmentList", Order=2)]
        public AttachmentType[] AttachmentList
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("EndManagmentDate", typeof(System.DateTime), DataType="date", Order=3)]
        public System.DateTime EndManagmentDate
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("IndefiniteManagement", typeof(bool), Order=4)]
        public bool IndefiniteManagement
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ManagerOKIType ManagerOKI
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public InfrastructureTypeOKIType OKIType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Services", Order=7)]
        public nsiRef[] Services
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public OKTMORefType OKTMO
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Adress
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public short CommissioningYear
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool IndependentSource
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal Deterioration
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public InfrastructureTypeObjectProperty ObjectProperty
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AddInfo
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AttachmentsEnergyEfficiency", Order=15)]
        public AttachmentType[] AttachmentsEnergyEfficiency
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class ManagerOKIType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("Municipalities", typeof(bool), Order=0)]
        public bool Municipalities
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RSO", typeof(ManagerOKITypeRSO), Order=1)]
        public ManagerOKITypeRSO RSO
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class ManagerOKITypeRSO
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string RSOOrganizationGUID
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Name
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class InfrastructureTypeOKIType : nsiRef
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ESubstationType", typeof(nsiRef), Order=0)]
        public nsiRef ESubstationType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("FuelType", typeof(nsiRef), Order=1)]
        public nsiRef FuelType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("GasNetworkType", typeof(nsiRef), Order=2)]
        public nsiRef GasNetworkType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("PowerPlantType", typeof(nsiRef), Order=3)]
        public nsiRef PowerPlantType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("WaterIntakeType", typeof(nsiRef), Order=4)]
        public nsiRef WaterIntakeType
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class InfrastructureTypeObjectProperty
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CountAccidents", typeof(string), DataType="nonNegativeInteger", Order=0)]
        public string CountAccidents
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("NetPieces", typeof(InfrastructureTypeObjectPropertyNetPieces), Order=1)]
        public InfrastructureTypeObjectPropertyNetPieces NetPieces
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OKILinks", typeof(InfrastructureTypeObjectPropertyOKILinks), Order=2)]
        public InfrastructureTypeObjectPropertyOKILinks OKILinks
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Resources", typeof(InfrastructureTypeObjectPropertyResources), Order=3)]
        public InfrastructureTypeObjectPropertyResources Resources
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("TransportationResources", typeof(InfrastructureTypeObjectPropertyTransportationResources), Order=4)]
        public InfrastructureTypeObjectPropertyTransportationResources TransportationResources
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class InfrastructureTypeObjectPropertyNetPieces
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Diameter
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Length
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal NeedReplaced
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal Wearout
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public nsiRef PressureType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public nsiRef VoltageType
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class InfrastructureTypeObjectPropertyOKILinks
    {
        
        [System.Xml.Serialization.XmlElementAttribute("SourceOKI", Order=0)]
        public string[] SourceOKI
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ReceiverOKI", Order=1)]
        public string[] ReceiverOKI
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class InfrastructureTypeObjectPropertyResources : ResourceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal SetPower
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal SitingPower
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class ResourceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public nsiRef MunicipalResource
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal TotalLoad
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal IndustrialLoad
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal SocialLoad
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal PopulationLoad
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class InfrastructureTypeObjectPropertyTransportationResources : ResourceType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal VolumeLosses
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public nsiRef CoolantType
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class importOKIRequest : BaseType
    {
        
        public importOKIRequest()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("RKIItem", Order=0)]
        public importOKIRequestRKIItem[] RKIItem
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class importOKIRequestRKIItem
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string OKIGUID
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OKI", typeof(importOKIRequestRKIItemOKI), Order=2)]
        public importOKIRequestRKIItemOKI OKI
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Termination", typeof(bool), Order=3)]
        public bool Termination
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class importOKIRequestRKIItemOKI : InfrastructureType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class exportOKIRequest : BaseType
    {
        
        public exportOKIRequest()
        {
            this.ExpiredManagement = true;
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("OKIType", Order=0)]
        public nsiRef[] OKIType
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ExpiredManagement
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OKTMORefType OKTMO
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string RSOOrganizationGUID
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class getStateResult : BaseAsyncResponseType
    {
        
        public getStateResult()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ExportOKIResult", typeof(exportOKIResultType), Order=1)]
        public exportOKIResultType ExportOKIResult
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ImportResult", typeof(CommonResultType), Order=2)]
        public CommonResultType ImportResult
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/")]
    public class exportOKIResult : BaseType
    {
        
        public exportOKIResult()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ExportOKIResult", typeof(exportOKIResultType), Order=1)]
        public exportOKIResultType ExportOKIResult
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
}
