//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.Nsi;
using Integration.Xmldsig;


namespace Integration.NsiServiceAsync
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-service-async/", ConfigurationName="NsiPortsTypeAsync")]
    public interface NsiPortsTypeAsync
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией importAdditionalServices не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importAdditionalServices", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importAdditionalServices", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        importAdditionalServicesResponseMessage importAdditionalServices(importAdditionalServicesRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией importMunicipalServices не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importMunicipalServices", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importMunicipalServices", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        importMunicipalServicesResponseMessage importMunicipalServices(importMunicipalServicesRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией importOrganizationWorks не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importOrganizationWorks", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importOrganizationWorks", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        importOrganizationWorksResponseMessage importOrganizationWorks(importOrganizationWorksRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getState", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:getState", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        getStateResponseMessage getState(getStateRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией exportDataProviderNsiItem не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportDataProviderNsiItem", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportDataProviderNsiItem", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        exportDataProviderNsiItemResponseMessage exportDataProviderNsiItem(exportDataProviderNsiItemRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией exportDataProviderPagingNsiItem не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportDataProviderPagingNsiItem", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportDataProviderPagingNsiItem", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        exportDataProviderPagingNsiItemResponseMessage exportDataProviderPagingNsiItem(exportDataProviderPagingNsiItemRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией importCapitalRepairWork не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importCapitalRepairWork", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importCapitalRepairWork", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        importCapitalRepairWorkResponseMessage importCapitalRepairWork(importCapitalRepairWorkRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией importBaseDecisionMSP не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importBaseDecisionMSP", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importBaseDecisionMSP", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        importBaseDecisionMSPResponseMessage importBaseDecisionMSP(importBaseDecisionMSPRequestMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importAdditionalServicesRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importAdditionalServicesRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public importAdditionalServicesRequest importAdditionalServicesRequest1;
        
        public importAdditionalServicesRequestMessage()
        {
        }
        
        public importAdditionalServicesRequestMessage(RequestHeader RequestHeader, importAdditionalServicesRequest importAdditionalServicesRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importAdditionalServicesRequest1 = importAdditionalServicesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importAdditionalServicesResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public importAdditionalServicesResponseMessage()
        {
        }
        
        public importAdditionalServicesResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importMunicipalServicesRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importMunicipalServicesRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public importMunicipalServicesRequest importMunicipalServicesRequest1;
        
        public importMunicipalServicesRequestMessage()
        {
        }
        
        public importMunicipalServicesRequestMessage(RequestHeader RequestHeader, importMunicipalServicesRequest importMunicipalServicesRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importMunicipalServicesRequest1 = importMunicipalServicesRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importMunicipalServicesResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public importMunicipalServicesResponseMessage()
        {
        }
        
        public importMunicipalServicesResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importOrganizationWorksRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importOrganizationWorksRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public importOrganizationWorksRequest importOrganizationWorksRequest1;
        
        public importOrganizationWorksRequestMessage()
        {
        }
        
        public importOrganizationWorksRequestMessage(RequestHeader RequestHeader, importOrganizationWorksRequest importOrganizationWorksRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importOrganizationWorksRequest1 = importOrganizationWorksRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importOrganizationWorksResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public importOrganizationWorksResponseMessage()
        {
        }
        
        public importOrganizationWorksResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStateRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public getStateRequest getStateRequest1;
        
        public getStateRequestMessage()
        {
        }
        
        public getStateRequestMessage(RequestHeader RequestHeader, getStateRequest getStateRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.getStateRequest1 = getStateRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public getStateResult getStateResult;
        
        public getStateResponseMessage()
        {
        }
        
        public getStateResponseMessage(ResultHeader ResultHeader, getStateResult getStateResult)
        {
            this.ResultHeader = ResultHeader;
            this.getStateResult = getStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportDataProviderNsiItemRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exportDataProviderNsiItemRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public exportDataProviderNsiItemRequest exportDataProviderNsiItemRequest1;
        
        public exportDataProviderNsiItemRequestMessage()
        {
        }
        
        public exportDataProviderNsiItemRequestMessage(RequestHeader RequestHeader, exportDataProviderNsiItemRequest exportDataProviderNsiItemRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.exportDataProviderNsiItemRequest1 = exportDataProviderNsiItemRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportDataProviderNsiItemResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public exportDataProviderNsiItemResponseMessage()
        {
        }
        
        public exportDataProviderNsiItemResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportDataProviderPagingNsiItemRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public exportDataProviderNsiPagingItemRequest exportDataProviderNsiPagingItemRequest;
        
        public exportDataProviderPagingNsiItemRequestMessage()
        {
        }
        
        public exportDataProviderPagingNsiItemRequestMessage(RequestHeader RequestHeader, exportDataProviderNsiPagingItemRequest exportDataProviderNsiPagingItemRequest)
        {
            this.RequestHeader = RequestHeader;
            this.exportDataProviderNsiPagingItemRequest = exportDataProviderNsiPagingItemRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportDataProviderPagingNsiItemResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public exportDataProviderPagingNsiItemResponseMessage()
        {
        }
        
        public exportDataProviderPagingNsiItemResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importCapitalRepairWorkRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importCapitalRepairWorkRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public importCapitalRepairWorkRequest importCapitalRepairWorkRequest1;
        
        public importCapitalRepairWorkRequestMessage()
        {
        }
        
        public importCapitalRepairWorkRequestMessage(RequestHeader RequestHeader, importCapitalRepairWorkRequest importCapitalRepairWorkRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importCapitalRepairWorkRequest1 = importCapitalRepairWorkRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importCapitalRepairWorkResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public importCapitalRepairWorkResponseMessage()
        {
        }
        
        public importCapitalRepairWorkResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importBaseDecisionMSPRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importBaseDecisionMSPRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi/", Order=0)]
        public importBaseDecisionMSPRequest importBaseDecisionMSPRequest1;
        
        public importBaseDecisionMSPRequestMessage()
        {
        }
        
        public importBaseDecisionMSPRequestMessage(RequestHeader RequestHeader, importBaseDecisionMSPRequest importBaseDecisionMSPRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importBaseDecisionMSPRequest1 = importBaseDecisionMSPRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importBaseDecisionMSPResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public importBaseDecisionMSPResponseMessage()
        {
        }
        
        public importBaseDecisionMSPResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NsiPortsTypeAsyncChannel : NsiPortsTypeAsync, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public class NsiPortsTypeAsyncClient : System.ServiceModel.ClientBase<NsiPortsTypeAsync>, NsiPortsTypeAsync
    {
        
        public NsiPortsTypeAsyncClient()
        {
        }
        
        public NsiPortsTypeAsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public NsiPortsTypeAsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NsiPortsTypeAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NsiPortsTypeAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importAdditionalServicesResponseMessage NsiPortsTypeAsync.importAdditionalServices(importAdditionalServicesRequestMessage request)
        {
            return base.Channel.importAdditionalServices(request);
        }
        
        public ResultHeader importAdditionalServices(RequestHeader RequestHeader, importAdditionalServicesRequest importAdditionalServicesRequest1, out AckRequest AckRequest)
        {
            importAdditionalServicesRequestMessage inValue = new importAdditionalServicesRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importAdditionalServicesRequest1 = importAdditionalServicesRequest1;
            importAdditionalServicesResponseMessage retVal = ((NsiPortsTypeAsync)(this)).importAdditionalServices(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importMunicipalServicesResponseMessage NsiPortsTypeAsync.importMunicipalServices(importMunicipalServicesRequestMessage request)
        {
            return base.Channel.importMunicipalServices(request);
        }
        
        public ResultHeader importMunicipalServices(RequestHeader RequestHeader, importMunicipalServicesRequest importMunicipalServicesRequest1, out AckRequest AckRequest)
        {
            importMunicipalServicesRequestMessage inValue = new importMunicipalServicesRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importMunicipalServicesRequest1 = importMunicipalServicesRequest1;
            importMunicipalServicesResponseMessage retVal = ((NsiPortsTypeAsync)(this)).importMunicipalServices(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importOrganizationWorksResponseMessage NsiPortsTypeAsync.importOrganizationWorks(importOrganizationWorksRequestMessage request)
        {
            return base.Channel.importOrganizationWorks(request);
        }
        
        public ResultHeader importOrganizationWorks(RequestHeader RequestHeader, importOrganizationWorksRequest importOrganizationWorksRequest1, out AckRequest AckRequest)
        {
            importOrganizationWorksRequestMessage inValue = new importOrganizationWorksRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importOrganizationWorksRequest1 = importOrganizationWorksRequest1;
            importOrganizationWorksResponseMessage retVal = ((NsiPortsTypeAsync)(this)).importOrganizationWorks(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getStateResponseMessage NsiPortsTypeAsync.getState(getStateRequestMessage request)
        {
            return base.Channel.getState(request);
        }
        
        public ResultHeader getState(RequestHeader RequestHeader, getStateRequest getStateRequest1, out getStateResult getStateResult)
        {
            getStateRequestMessage inValue = new getStateRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.getStateRequest1 = getStateRequest1;
            getStateResponseMessage retVal = ((NsiPortsTypeAsync)(this)).getState(inValue);
            getStateResult = retVal.getStateResult;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        exportDataProviderNsiItemResponseMessage NsiPortsTypeAsync.exportDataProviderNsiItem(exportDataProviderNsiItemRequestMessage request)
        {
            return base.Channel.exportDataProviderNsiItem(request);
        }
        
        public ResultHeader exportDataProviderNsiItem(RequestHeader RequestHeader, exportDataProviderNsiItemRequest exportDataProviderNsiItemRequest1, out AckRequest AckRequest)
        {
            exportDataProviderNsiItemRequestMessage inValue = new exportDataProviderNsiItemRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.exportDataProviderNsiItemRequest1 = exportDataProviderNsiItemRequest1;
            exportDataProviderNsiItemResponseMessage retVal = ((NsiPortsTypeAsync)(this)).exportDataProviderNsiItem(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        exportDataProviderPagingNsiItemResponseMessage NsiPortsTypeAsync.exportDataProviderPagingNsiItem(exportDataProviderPagingNsiItemRequestMessage request)
        {
            return base.Channel.exportDataProviderPagingNsiItem(request);
        }
        
        public ResultHeader exportDataProviderPagingNsiItem(RequestHeader RequestHeader, exportDataProviderNsiPagingItemRequest exportDataProviderNsiPagingItemRequest, out AckRequest AckRequest)
        {
            exportDataProviderPagingNsiItemRequestMessage inValue = new exportDataProviderPagingNsiItemRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.exportDataProviderNsiPagingItemRequest = exportDataProviderNsiPagingItemRequest;
            exportDataProviderPagingNsiItemResponseMessage retVal = ((NsiPortsTypeAsync)(this)).exportDataProviderPagingNsiItem(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importCapitalRepairWorkResponseMessage NsiPortsTypeAsync.importCapitalRepairWork(importCapitalRepairWorkRequestMessage request)
        {
            return base.Channel.importCapitalRepairWork(request);
        }
        
        public ResultHeader importCapitalRepairWork(RequestHeader RequestHeader, importCapitalRepairWorkRequest importCapitalRepairWorkRequest1, out AckRequest AckRequest)
        {
            importCapitalRepairWorkRequestMessage inValue = new importCapitalRepairWorkRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importCapitalRepairWorkRequest1 = importCapitalRepairWorkRequest1;
            importCapitalRepairWorkResponseMessage retVal = ((NsiPortsTypeAsync)(this)).importCapitalRepairWork(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importBaseDecisionMSPResponseMessage NsiPortsTypeAsync.importBaseDecisionMSP(importBaseDecisionMSPRequestMessage request)
        {
            return base.Channel.importBaseDecisionMSP(request);
        }
        
        public ResultHeader importBaseDecisionMSP(RequestHeader RequestHeader, importBaseDecisionMSPRequest importBaseDecisionMSPRequest1, out AckRequest AckRequest)
        {
            importBaseDecisionMSPRequestMessage inValue = new importBaseDecisionMSPRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importBaseDecisionMSPRequest1 = importBaseDecisionMSPRequest1;
            importBaseDecisionMSPResponseMessage retVal = ((NsiPortsTypeAsync)(this)).importBaseDecisionMSP(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
    }
}
