//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.NsiBase;
using Integration.OrganizationsRegistryBase;


namespace Integration.OrganizationsRegistry
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class ForeignBranchImportType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CreateForeignBranch", typeof(ForeignBranchType), Order=0)]
        public ForeignBranchType CreateForeignBranch
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("UpdateForeignBranch", typeof(ForeignBranchImportTypeUpdateForeignBranch), Order=1)]
        public ForeignBranchImportTypeUpdateForeignBranch UpdateForeignBranch
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class ForeignBranchImportTypeUpdateForeignBranch
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry-base/", Order=0)]
        public string orgVersionGUID
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ShortName
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=3)]
        public string INN
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=4)]
        public string KPP
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Address
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FIASHouseGuid
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime AccreditationStartDate
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime AccreditationEndDate
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RegistrationCountry
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class SubsidiaryImportType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CreateSubsidiary", typeof(SubsidiaryImportTypeCreateSubsidiary), Order=0)]
        public SubsidiaryImportTypeCreateSubsidiary CreateSubsidiary
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("UpdateSubsidiary", typeof(SubsidiaryImportTypeUpdateSubsidiary), Order=1)]
        public SubsidiaryImportTypeUpdateSubsidiary UpdateSubsidiary
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class SubsidiaryImportTypeCreateSubsidiary : SubsidiaryType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry-base/", Order=0)]
        public string orgVersionGUID
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class SubsidiaryImportTypeUpdateSubsidiary
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry-base/", Order=0)]
        public string orgVersionGUID
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FullName
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=2)]
        public string INN
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-base/", Order=3)]
        public string OKOPF
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Address
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string FIASHouseGuid
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=6)]
        public System.DateTime ActivityEndDate
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public SubsidiaryImportTypeUpdateSubsidiarySourceName SourceName
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class SubsidiaryImportTypeUpdateSubsidiarySourceName
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="date")]
        public System.DateTime Date
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class getStateResult : BaseAsyncResponseType
    {
        
        public getStateResult()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ImportResult", typeof(CommonResultType), Order=1)]
        public CommonResultType ImportResult
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class importSubsidiaryRequest : BaseType
    {
        
        public importSubsidiaryRequest()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Subsidiary", Order=0)]
        public importSubsidiaryRequestSubsidiary[] Subsidiary
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class importSubsidiaryRequestSubsidiary : SubsidiaryImportType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class importForeignBranchRequest : BaseType
    {
        
        public importForeignBranchRequest()
        {
            this.version = "11.1.0.3";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ForeignBranch", Order=0)]
        public importForeignBranchRequestForeignBranch[] ForeignBranch
        {
            get;
            set;
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version
        {
            get;
            set;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/organizations-registry/")]
    public class importForeignBranchRequestForeignBranch : ForeignBranchImportType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID
        {
            get;
            set;
        }
    }
}
