//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Xmldsig;


namespace Integration.Base
{
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class RequestHeader : HeaderType
    {
        
        public RequestHeader()
        {
            this.IsOperatorSignature = true;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("SenderID", typeof(string), Order=0)]
        public string SenderID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("orgPPAGUID", typeof(string), Order=1)]
        public string orgPPAGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsOperatorSignature { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class HeaderType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime Date { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class AttachmentType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Attachment Attachment { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AttachmentHASH { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class Attachment
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AttachmentGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class ErrorMessageType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string StackTrace { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class CommonResultType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string GUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string TransportGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Error", typeof(CommonResultTypeError), Order=2)]
        public CommonResultTypeError Error { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UniqueNumber", typeof(string), Order=3)]
        public string UniqueNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UpdateDate", typeof(System.DateTime), Order=4)]
        public System.DateTime UpdateDate { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class CommonResultTypeError : ErrorMessageType
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BaseAsyncResponseType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class BaseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", Order=0)]
        public SignatureType Signature { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Id { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class BaseAsyncResponseType : BaseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public sbyte RequestState { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class getStateRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageGUID { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ErrorMessageType ErrorMessage { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class ResultHeader : HeaderType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class AckRequest
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AckRequestAck Ack { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class AckRequestAck
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequesterMessageGUID { get; set; }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class Fault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public string ErrorCode { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ErrorMessage { get; set; }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StackTrace { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class DocumentPortalType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime ApproveDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AttachmentType Attachment { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class OKTMORefType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class RegionType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string code { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string name { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class ResultType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("TransportGUID", typeof(string), Order=0)]
        public string TransportGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UpdateGUID", typeof(string), Order=1)]
        public string UpdateGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CreateOrUpdateError", typeof(ErrorMessageType), Order=2)]
        public ErrorMessageType CreateOrUpdateError { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("GUID", typeof(string), Order=3)]
        public string GUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UniqueNumber", typeof(string), Order=4)]
        public string UniqueNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UpdateDate", typeof(System.DateTime), Order=5)]
        public System.DateTime UpdateDate { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class ImportResult : BaseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CommonResult", typeof(CommonResultType), Order=0)]
        public CommonResultType CommonResult { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Order=1)]
        public ErrorMessageType ErrorMessage { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
    public class ImportResult1 : BaseType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CommonResult", typeof(CommonResultType), Order=0)]
        public CommonResultType CommonResult { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Order=1)]
        public ErrorMessageType ErrorMessage { get; set; }
    }
}
