//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.NsiBase;
using Integration.OrganizationsRegistryBase;
using Integration.PaymentsBase;


namespace Integration.Bills
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class AnnulmentType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReasonOfAnnulment { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ReportPeriodIKUInfoType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Paid { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SupportingDocuments", Order=1)]
        public AttachmentType[] SupportingDocuments { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ReportPeriodRSOInfoType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Credted { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Receipt { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Debts { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal Overpayment { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SupportingDocuments", Order=4)]
        public AttachmentType[] SupportingDocuments { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ReportPeriodType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public int Month { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=1)]
        public short Year { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ExportSettlementResultType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SettlementGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ExportSettlementResultTypeContract Contract { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportingPeriod", Order=2)]
        public ExportSettlementResultTypeReportingPeriod[] ReportingPeriod { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ExportSettlementResultTypeAnnuled Annuled { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ExportSettlementResultTypeContract
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ContractRootGUID", typeof(string), Order=0)]
        public string ContractRootGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NoContract", typeof(ExportSettlementResultTypeContractNoContract), Order=1)]
        public ExportSettlementResultTypeContractNoContract NoContract { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ExportSettlementResultTypeContractNoContract
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RegOrgType FirstContractParty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocNum { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime SigningDate { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ExportSettlementResultTypeReportingPeriod : ReportPeriodType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ReportPeriodIKUInfo", typeof(ReportPeriodIKUInfoType), Order=0)]
        public ReportPeriodIKUInfoType ReportPeriodIKUInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportPeriodRSOInfo", typeof(ReportPeriodRSOInfoType), Order=1)]
        public ReportPeriodRSOInfoType ReportPeriodRSOInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ExportSettlementResultTypeReportingPeriodReportPeriodStatus ReportPeriodStatus { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ExportSettlementResultTypeReportingPeriodReportPeriodStatus
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExportSettlementResultTypeReportingPeriodReportPeriodStatusStatus Status { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ReasonOfAnnulment { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum ExportSettlementResultTypeReportingPeriodReportPeriodStatusStatus
    {
        
        /// <remarks/>
        Posted,
        
        /// <remarks/>
        Draft,
        
        /// <remarks/>
        Annul,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ExportSettlementResultTypeAnnuled
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ReasonOfAnnulment { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class InsuranceProductType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttachmentType Description { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string InsuranceOrg { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportNotificationsOfOrderExecutionResultType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("NotificationOfOrderExecutionWithStatus", Order=0)]
        public exportNotificationsOfOrderExecutionResultTypeNotificationOfOrderExecutionWithStatus[] NotificationOfOrderExecutionWithStatus { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportNotificationsOfOrderExecutionResultTypeNotificationOfOrderExecutionWithStatus : NotificationOfOrderExecutionExportType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public sbyte AckStatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime CreationDate { get; set; }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AcknowledgmentRequest", IsNullable=false)]
        public exportNotificationsOfOrderExecutionResultTypeNotificationOfOrderExecutionWithStatusAcknowledgmentRequest[] AcknowledgmentRequestsList { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public long AcknowledgmentAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/payments-base/", Order=4)]
        public string NotificationsOfOrderExecutionGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string orgPPAGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportNotificationsOfOrderExecutionResultTypeNotificationOfOrderExecutionWithStatusAcknowledgmentRequest : AcknowledgmentRequestInfoExportType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/payments-base/", Order=0)]
        public string OrderID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceDebtType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalService", typeof(PDServiceDebtTypeAdditionalService), Order=0)]
        public PDServiceDebtTypeAdditionalService AdditionalService { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("HousingService", typeof(PDServiceDebtTypeHousingService), Order=1)]
        public PDServiceDebtTypeHousingService HousingService { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MunicipalService", typeof(PDServiceDebtTypeMunicipalService), Order=2)]
        public PDServiceDebtTypeMunicipalService MunicipalService { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceDebtTypeAdditionalService : ServiceDebtType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ServiceDebtType : DebtType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public nsiRef ServiceType { get; set; }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ServiceDebtType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class DebtType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public int Month { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=1)]
        public short Year { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TotalPayable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string orgPPAGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceDebtTypeHousingService : ServiceDebtType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceDebtTypeMunicipalService : ServiceDebtType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class CapitalRepairType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal Contribution { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal AccountingPeriodTotal { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal MoneyRecalculation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal MoneyDiscount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal TotalPayable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string orgPPAGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ServiceInformationType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal individualConsumptionCurrentValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal houseOverallNeedsCurrentValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal houseTotalIndividualConsumption { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal houseTotalHouseOverallNeeds { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ServiceChargeType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal MoneyRecalculation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal MoneyDiscount { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ServicePDType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public nsiRef ServiceType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Rate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TotalPayable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal AccountingPeriodTotal { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CalcExplanation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string orgPPAGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AdditionalService", typeof(PDServiceChargeTypeAdditionalService), Order=0)]
        public PDServiceChargeTypeAdditionalService AdditionalService { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("HousingService", typeof(PDServiceChargeTypeHousingService), Order=1)]
        public PDServiceChargeTypeHousingService HousingService { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MunicipalService", typeof(PDServiceChargeTypeMunicipalService), Order=2)]
        public PDServiceChargeTypeMunicipalService MunicipalService { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeAdditionalService : ServicePDType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceChargeType ServiceCharge { get; set; }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Volume", IsNullable=false)]
        public PDServiceChargeTypeAdditionalServiceVolume[] Consumption { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeAdditionalServiceVolume
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeTypeAdditionalServiceVolumeType type { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeTypeAdditionalServiceVolumeType
    {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeHousingService : ServicePDType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceChargeType ServiceCharge { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PDServiceChargeTypeHousingServiceConsumption Consumption { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeHousingServiceConsumption
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PDServiceChargeTypeHousingServiceConsumptionVolume Volume { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeHousingServiceConsumptionVolume
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeTypeHousingServiceConsumptionVolumeType type { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeTypeHousingServiceConsumptionVolumeType
    {
        
        /// <remarks/>
        I,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeMunicipalService : ServicePDType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ServiceChargeType ServiceCharge { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PiecemealPayment PiecemealPayment { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PDServiceChargeTypeMunicipalServicePaymentRecalculation PaymentRecalculation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ServiceInformation ServiceInformation { get; set; }
        
        [System.Xml.Serialization.XmlArrayAttribute(Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Volume", IsNullable=false)]
        public PDServiceChargeTypeMunicipalServiceVolume[] Consumption { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal MunicipalServiceIndividualConsumptionPayable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal MunicipalServiceCommunalConsumptionPayable { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PiecemealPayment
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal paymentPeriodPiecemealPaymentSum { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal pastPaymentPeriodPiecemealPaymentSum { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal piecemealPaymentPercentRub { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal piecemealPaymentPercent { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal piecemealPaymentSum { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeMunicipalServicePaymentRecalculation
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string recalculationReason { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal sum { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class ServiceInformation : ServiceInformationType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public decimal houseOverallNeedsNorm { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal individualConsumptionNorm { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PDServiceChargeTypeMunicipalServiceVolume
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeTypeMunicipalServiceVolumeType type { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PDServiceChargeTypeMunicipalServiceVolumeDeterminingMethod determiningMethod { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeTypeMunicipalServiceVolumeType
    {
        
        /// <remarks/>
        I,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PDServiceChargeTypeMunicipalServiceVolumeDeterminingMethod
    {
        
        /// <remarks/>
        N,
        
        /// <remarks/>
        M,
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PaymentDocumentType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/", Order=0)]
        public string AccountGuid { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=1)]
        public string PaymentDocumentNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PaymentDocumentTypeAddressInfo AddressInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CapitalRepairCharge", typeof(CapitalRepairType), Order=3)]
        public CapitalRepairType CapitalRepairCharge { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CapitalRepairDebt", typeof(DebtType), Order=4)]
        public DebtType CapitalRepairDebt { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ChargeDebt", typeof(PDServiceDebtType), Order=5)]
        public PDServiceDebtType ChargeDebt { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ChargeInfo", typeof(PaymentDocumentTypeChargeInfo), Order=6)]
        public PaymentDocumentTypeChargeInfo ChargeInfo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Insurance", typeof(PaymentDocumentTypeInsurance), Order=7)]
        public PaymentDocumentTypeInsurance Insurance { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Expose", typeof(bool), Order=8)]
        public bool Expose { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Withdraw", typeof(bool), Order=9)]
        public bool Withdraw { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal DebtPreviousPeriods { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal AdvanceBllingPeriod { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal totalPiecemealPaymentSum { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public sbyte PaymentsTaken { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PaymentDocumentTypeAddressInfo
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public sbyte LivingPersonsNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal ResidentialSquare { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal HeatedArea { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal TotalSquare { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PaymentDocumentTypeChargeInfo : PDServiceChargeType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PaymentDocumentTypeInsurance
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InsuranceProductGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public decimal Rate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal TotalPayable { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public decimal AccountingPeriodTotal { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string CalcExplanation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public ServiceChargeType ServiceCharge { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public PaymentDocumentTypeInsuranceConsumption Consumption { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PaymentDocumentTypeInsuranceConsumption
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PaymentDocumentTypeInsuranceConsumptionVolume Volume { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class PaymentDocumentTypeInsuranceConsumptionVolume
    {
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public PaymentDocumentTypeInsuranceConsumptionVolumeType type { get; set; }
        
        [System.Xml.Serialization.XmlTextAttribute()]
        public decimal Value { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public enum PaymentDocumentTypeInsuranceConsumptionVolumeType
    {
        
        /// <remarks/>
        I,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportPaymentDocumentResultType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentDocument", typeof(exportPaymentDocumentResultTypePaymentDocument), Order=1)]
        public exportPaymentDocumentResultTypePaymentDocument PaymentDocument { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportPaymentDocumentResultTypePaymentDocument : PaymentDocumentType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=0)]
        public string PaymentDocumentID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PaymentInformationType PaymentInformation { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class getStateResult : BaseAsyncResponseType
    {
        
        public getStateResult()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ImportResult", typeof(CommonResultType), Order=1)]
        public CommonResultType ImportResult { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("InsuranceProduct", typeof(InsuranceProductType), Order=2)]
        public InsuranceProductType InsuranceProduct { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Settlement", typeof(ExportSettlementResultType), Order=3)]
        public ExportSettlementResultType Settlement { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportNotificationsOfOrderExecutionResult", typeof(exportNotificationsOfOrderExecutionResultType), Order=4)]
        public exportNotificationsOfOrderExecutionResultType exportNotificationsOfOrderExecutionResult { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportPaymentDocResult", typeof(exportPaymentDocumentResultType), Order=5)]
        public exportPaymentDocumentResultType exportPaymentDocResult { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importPaymentDocumentRequest : BaseType
    {
        
        public importPaymentDocumentRequest()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Month", typeof(int), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public int Month { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Year", typeof(short), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=1)]
        public short Year { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentDocument", typeof(importPaymentDocumentRequestPaymentDocument), Order=2)]
        public importPaymentDocumentRequestPaymentDocument PaymentDocument { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentInformation", typeof(importPaymentDocumentRequestPaymentInformation), Order=3)]
        public importPaymentDocumentRequestPaymentInformation PaymentInformation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("WithdrawPaymentDocument", typeof(importPaymentDocumentRequestWithdrawPaymentDocument), Order=4)]
        public importPaymentDocumentRequestWithdrawPaymentDocument WithdrawPaymentDocument { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importPaymentDocumentRequestPaymentDocument : PaymentDocumentType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=1)]
        public string PaymentDocumentID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PaymentInformationKey { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importPaymentDocumentRequestPaymentInformation : PaymentInformationKeyType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importPaymentDocumentRequestWithdrawPaymentDocument
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=1)]
        public string PaymentDocumentID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportPaymentDocumentRequest : BaseType
    {
        
        public exportPaymentDocumentRequest()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AccountNumber", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/", Order=0)]
        public string AccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ServiceID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/", Order=1)]
        public string ServiceID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UnifiedAccountNumber", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/", Order=2)]
        public string UnifiedAccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Month", typeof(int), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=3)]
        public int Month { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Year", typeof(short), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=4)]
        public short Year { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentDocumentID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=5)]
        public string PaymentDocumentID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentDocumentNumber", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=6)]
        public string PaymentDocumentNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("FIASHouseGuid", typeof(string), Order=7)]
        public string FIASHouseGuid { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportNotificationsOfOrderExecutionRequest : BaseType
    {
        
        public exportNotificationsOfOrderExecutionRequest()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("Notifications", typeof(exportNotificationsOfOrderExecutionRequestNotifications), Order=0)]
        public exportNotificationsOfOrderExecutionRequestNotifications Notifications { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SupplierIDs", typeof(exportNotificationsOfOrderExecutionRequestSupplierIDs), Order=1)]
        public exportNotificationsOfOrderExecutionRequestSupplierIDs SupplierIDs { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportNotificationsOfOrderExecutionRequestNotifications
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AckStatus", typeof(sbyte), Order=0)]
        public sbyte AckStatus { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DateFrom", typeof(System.DateTime), DataType="date", Order=1)]
        public System.DateTime DateFrom { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("DaysInterval", typeof(sbyte), Order=2)]
        public sbyte DaysInterval { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NotificationsOfOrderExecutionGUID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/payments-base/", Order=3)]
        public string NotificationsOfOrderExecutionGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportNotificationsOfOrderExecutionRequestSupplierIDs
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AccountNumber", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/", Order=0)]
        public string AccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ServiceID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/", Order=1)]
        public string ServiceID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("UnifiedAccountNumber", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/account-base/", Order=2)]
        public string UnifiedAccountNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Month", typeof(int), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=3)]
        public int Month { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Year", typeof(short), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=4)]
        public short Year { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentDocumentID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=5)]
        public string PaymentDocumentID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentDocumentNumber", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=6)]
        public string PaymentDocumentNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("FIASHouseGuid", typeof(string), Order=7)]
        public string FIASHouseGuid { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importAcknowledgmentRequest : BaseType
    {
        
        public importAcknowledgmentRequest()
        {
            this.version = "11.0.0.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("AckCancellation", typeof(importAcknowledgmentRequestAckCancellation), Order=0)]
        public importAcknowledgmentRequestAckCancellation AckCancellation { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AcknowledgmentRequestInfo", typeof(importAcknowledgmentRequestAcknowledgmentRequestInfo), Order=1)]
        public importAcknowledgmentRequestAcknowledgmentRequestInfo AcknowledgmentRequestInfo { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importAcknowledgmentRequestAckCancellation
    {
        
        [System.Xml.Serialization.XmlElementAttribute("orgPPAGUID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string orgPPAGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NotificationsOfOrderExecutionGUID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/payments-base/", Order=1)]
        public string NotificationsOfOrderExecutionGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OrderID", typeof(string), Namespace="http://dom.gosuslugi.ru/schema/integration/payments-base/", Order=2)]
        public string OrderID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/bills-base/", Order=3)]
        public string PaymentDocumentID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=4)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importAcknowledgmentRequestAcknowledgmentRequestInfo : AcknowledgmentRequestInfoType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importInsuranceProductRequest : BaseType
    {
        
        public importInsuranceProductRequest()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("InsuranceProduct", Order=0)]
        public importInsuranceProductRequestInsuranceProduct[] InsuranceProduct { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importInsuranceProductRequestInsuranceProduct
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("CreateOrUpdate", typeof(importInsuranceProductRequestInsuranceProductCreateOrUpdate), Order=1)]
        public importInsuranceProductRequestInsuranceProductCreateOrUpdate CreateOrUpdate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Remove", typeof(importInsuranceProductRequestInsuranceProductRemove), Order=2)]
        public importInsuranceProductRequestInsuranceProductRemove Remove { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importInsuranceProductRequestInsuranceProductCreateOrUpdate : InsuranceProductType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InsuranceProductGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importInsuranceProductRequestInsuranceProductRemove
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string InsuranceProductGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime CloseDate { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportInsuranceProductRequest : BaseType
    {
        
        public exportInsuranceProductRequest()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importRSOSettlementsRequest : BaseType
    {
        
        public importRSOSettlementsRequest()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("importSettlement", Order=0)]
        public importRSOSettlementsRequestImportSettlement[] importSettlement { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importRSOSettlementsRequestImportSettlement
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SettlementGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AnnulmentSettlement", typeof(AnnulmentType), Order=2)]
        public AnnulmentType AnnulmentSettlement { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Settlement", typeof(importRSOSettlementsRequestImportSettlementSettlement), Order=3)]
        public importRSOSettlementsRequestImportSettlementSettlement Settlement { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importRSOSettlementsRequestImportSettlementSettlement
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public importRSOSettlementsRequestImportSettlementSettlementContract Contract { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportingPeriod", Order=1)]
        public importRSOSettlementsRequestImportSettlementSettlementReportingPeriod[] ReportingPeriod { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importRSOSettlementsRequestImportSettlementSettlementContract
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ContractRootGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importRSOSettlementsRequestImportSettlementSettlementReportingPeriod : ReportPeriodType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AnnulmentReportingPeriod", typeof(importRSOSettlementsRequestImportSettlementSettlementReportingPeriodAnnulmentReportingPeriod), Order=0)]
        public importRSOSettlementsRequestImportSettlementSettlementReportingPeriodAnnulmentReportingPeriod AnnulmentReportingPeriod { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportingPeriodInfo", typeof(ReportPeriodRSOInfoType), Order=1)]
        public ReportPeriodRSOInfoType ReportingPeriodInfo { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importRSOSettlementsRequestImportSettlementSettlementReportingPeriodAnnulmentReportingPeriod : AnnulmentType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importIKUSettlementsRequest : BaseType
    {
        
        public importIKUSettlementsRequest()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("importSettlement", Order=0)]
        public importIKUSettlementsRequestImportSettlement[] importSettlement { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importIKUSettlementsRequestImportSettlement
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public string TransportGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SettlementGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("AnnulmentSettlement", typeof(AnnulmentType), Order=2)]
        public AnnulmentType AnnulmentSettlement { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Settlement", typeof(importIKUSettlementsRequestImportSettlementSettlement), Order=3)]
        public importIKUSettlementsRequestImportSettlementSettlement Settlement { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importIKUSettlementsRequestImportSettlementSettlement
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public importIKUSettlementsRequestImportSettlementSettlementContract Contract { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportingPeriod", Order=1)]
        public importIKUSettlementsRequestImportSettlementSettlementReportingPeriod[] ReportingPeriod { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importIKUSettlementsRequestImportSettlementSettlementContract
    {
        
        [System.Xml.Serialization.XmlElementAttribute("ContractRootGUID", typeof(string), Order=0)]
        public string ContractRootGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NoContract", typeof(importIKUSettlementsRequestImportSettlementSettlementContractNoContract), Order=1)]
        public importIKUSettlementsRequestImportSettlementSettlementContractNoContract NoContract { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importIKUSettlementsRequestImportSettlementSettlementContractNoContract
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RegOrgType FirstContractParty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocNum { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime SigningDate { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importIKUSettlementsRequestImportSettlementSettlementReportingPeriod : ReportPeriodType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("AnnulmentReportingPeriod", typeof(importIKUSettlementsRequestImportSettlementSettlementReportingPeriodAnnulmentReportingPeriod), Order=0)]
        public importIKUSettlementsRequestImportSettlementSettlementReportingPeriodAnnulmentReportingPeriod AnnulmentReportingPeriod { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ReportingPeriodInfo", typeof(ReportPeriodIKUInfoType), Order=1)]
        public ReportPeriodIKUInfoType ReportingPeriodInfo { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class importIKUSettlementsRequestImportSettlementSettlementReportingPeriodAnnulmentReportingPeriod : AnnulmentType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportSettlementsRequest : BaseType
    {
        
        public exportSettlementsRequest()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ContractNumber", typeof(string), Order=0)]
        public string ContractNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ContractRootGUID", typeof(string), Order=1)]
        public string ContractRootGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OtherContractParty", typeof(RegOrgType), Order=2)]
        public RegOrgType OtherContractParty { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Period", typeof(exportSettlementsRequestPeriod), Order=3)]
        public exportSettlementsRequestPeriod Period { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("SettlementGUID", typeof(string), Order=4)]
        public string SettlementGUID { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportSettlementsRequestPeriod
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReportPeriodType PeriodFrom { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ReportPeriodType PeriodTo { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportPaymentDocumentResult : BaseType
    {
        
        public exportPaymentDocumentResult()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PaymentDocument", typeof(exportPaymentDocumentResultType), Order=1)]
        public exportPaymentDocumentResultType PaymentDocument { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportNotificationsOfOrderExecutionResult : BaseType
    {
        
        public exportNotificationsOfOrderExecutionResult()
        {
            this.version = "11.0.0.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportNotificationsOfOrderExecutionResult", typeof(exportNotificationsOfOrderExecutionResultType), Order=1)]
        public exportNotificationsOfOrderExecutionResultType exportNotificationsOfOrderExecutionResultType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportInsuranceProductResult : BaseType
    {
        
        public exportInsuranceProductResult()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("InsuranceProduct", typeof(InsuranceProductType), Order=1)]
        public InsuranceProductType InsuranceProduct { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/bills/")]
    public class exportSettlementsResult : BaseType
    {
        
        public exportSettlementsResult()
        {
            this.version = "10.0.2.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("Settlement", typeof(ExportSettlementResultType), Order=1)]
        public ExportSettlementResultType Settlement { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
}
