//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.MeteringDeviceBase;
using Integration.NsiBase;


namespace Integration.DeviceMetering
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportElectricMeteringValueKindType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CurrentValue", Order=0)]
        public ExportElectricMeteringValueKindTypeCurrentValue[] CurrentValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ControlValue", Order=1)]
        public ExportElectricMeteringValueKindTypeControlValue[] ControlValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationValue", Order=2)]
        public ExportElectricMeteringValueKindTypeVerificationValue[] VerificationValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportElectricMeteringValueKindTypeCurrentValue : ExportElectricMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DateValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportElectricMeteringValueKindTypeControlValue : ExportElectricMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportElectricMeteringValueKindTypeVerificationValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime StartDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime EndDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime SealDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ExportElectricMeteringValueType StartValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ExportElectricMeteringValueType EndValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PlannedVerification", typeof(bool), Order=5)]
        public bool PlannedVerification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationReason", typeof(nsiRef), Order=6)]
        public nsiRef VerificationReason { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportOneRateMeteringValueKindType
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CurrentValue", Order=0)]
        public ExportOneRateMeteringValueKindTypeCurrentValue[] CurrentValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ControlValue", Order=1)]
        public ExportOneRateMeteringValueKindTypeControlValue[] ControlValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationValue", Order=2)]
        public ExportOneRateMeteringValueKindTypeVerificationValue[] VerificationValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportOneRateMeteringValueKindTypeCurrentValue : ExportOneRateMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime DateValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportOneRateMeteringValueKindTypeControlValue : ExportOneRateMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class ExportOneRateMeteringValueKindTypeVerificationValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime StartDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime EndDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime SealDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StartValue", Order=3)]
        public ExportOneRateMeteringValueType[] StartValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("EndValue", Order=4)]
        public ExportOneRateMeteringValueType[] EndValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PlannedVerification", typeof(bool), Order=5)]
        public bool PlannedVerification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationReason", typeof(nsiRef), Order=6)]
        public nsiRef VerificationReason { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryResultType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MeteringDeviceRootGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ElectricDeviceValue", typeof(exportMeteringDeviceHistoryResultTypeElectricDeviceValue), Order=1)]
        public exportMeteringDeviceHistoryResultTypeElectricDeviceValue ElectricDeviceValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OneRateDeviceValue", typeof(exportMeteringDeviceHistoryResultTypeOneRateDeviceValue), Order=2)]
        public exportMeteringDeviceHistoryResultTypeOneRateDeviceValue OneRateDeviceValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public exportMeteringDeviceHistoryResultTypeArchivedValues ArchivedValues { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryResultTypeElectricDeviceValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExportElectricMeteringValueType BaseValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public exportMeteringDeviceHistoryResultTypeElectricDeviceValueValues Values { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryResultTypeElectricDeviceValueValues : ExportElectricMeteringValueKindType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool excludeISValues { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryResultTypeOneRateDeviceValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExportOneRateMeteringValueType BaseValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public exportMeteringDeviceHistoryResultTypeOneRateDeviceValueValues Values { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryResultTypeOneRateDeviceValueValues : ExportOneRateMeteringValueKindType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool excludeISValues { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryResultTypeArchivedValues
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public nsiRef ArchivingReason { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequest : BaseType
    {
        
        public importMeteringDeviceValuesRequest()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FIASHouseGuid { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MeteringDevicesValues", Order=1)]
        public importMeteringDeviceValuesRequestMeteringDevicesValues[] MeteringDevicesValues { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValues
    {
        
        [System.Xml.Serialization.XmlElementAttribute("MeteringDeviceRootGUID", typeof(string), Order=0)]
        public string MeteringDeviceRootGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MeteringDeviceVersionGUID", typeof(string), Order=1)]
        public string MeteringDeviceVersionGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ElectricDeviceValue", typeof(importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValue), Order=2)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValue ElectricDeviceValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("OneRateDeviceValue", typeof(importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValue), Order=3)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValue OneRateDeviceValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CurrentValue", Order=0)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValueCurrentValue[] CurrentValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ControlValue", Order=1)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValueControlValue[] ControlValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationValue", Order=2)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValueVerificationValue[] VerificationValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValueCurrentValue : ElectricMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=1)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValueControlValue : ElectricMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=1)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesElectricDeviceValueVerificationValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime StartDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime EndDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime SealDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public ElectricMeteringValueType StartValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ElectricMeteringValueType EndValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PlannedVerification", typeof(bool), Order=5)]
        public bool PlannedVerification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationReason", typeof(nsiRef), Order=6)]
        public nsiRef VerificationReason { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=7)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute("CurrentValue", Order=0)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValueCurrentValue[] CurrentValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ControlValue", Order=1)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValueControlValue[] ControlValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValueVerificationValue VerificationValue { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValueCurrentValue : OneRateMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=1)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValueControlValue : OneRateMeteringValueType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime DateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=1)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class importMeteringDeviceValuesRequestMeteringDevicesValuesOneRateDeviceValueVerificationValue
    {
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime StartDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=1)]
        public System.DateTime EndDateValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=2)]
        public System.DateTime SealDate { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("StartValue", Order=3)]
        public OneRateMeteringValueType[] StartValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("EndValue", Order=4)]
        public OneRateMeteringValueType[] EndValue { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("PlannedVerification", typeof(bool), Order=5)]
        public bool PlannedVerification { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("VerificationReason", typeof(nsiRef), Order=6)]
        public nsiRef VerificationReason { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=7)]
        public string TransportGUID { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryRequest : BaseType
    {
        
        public exportMeteringDeviceHistoryRequest()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FIASHouseGuid { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MeteringDeviceRootGUID", typeof(string), Order=1)]
        public string MeteringDeviceRootGUID { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MeteringDeviceType", typeof(nsiRef), Order=2)]
        public nsiRef MeteringDeviceType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("MunicipalResource", typeof(nsiRef), Order=3)]
        public nsiRef MunicipalResource { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime CommissioningDateFrom { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime CommissioningDateTo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool SerchArchived { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime ArchiveDateFrom { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=8)]
        public System.DateTime ArchiveDateTo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime inputDateFrom { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=10)]
        public System.DateTime inputDateTo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool excludeISValues { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class getStateResult : BaseAsyncResponseType
    {
        
        public getStateResult()
        {
            this.version = "10.0.1.1";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("ImportResult", typeof(CommonResultType), Order=1)]
        public CommonResultType ImportResult { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportMeteringDeviceHistoryResult", typeof(exportMeteringDeviceHistoryResultType), Order=2)]
        public exportMeteringDeviceHistoryResultType exportMeteringDeviceHistoryResult { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/device-metering/")]
    public class exportMeteringDeviceHistoryResult : BaseType
    {
        
        public exportMeteringDeviceHistoryResult()
        {
            this.version = "11.1.0.8";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("exportMeteringDeviceHistoryResult", typeof(exportMeteringDeviceHistoryResultType), Order=1)]
        public exportMeteringDeviceHistoryResultType exportMeteringDeviceHistoryResultType { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
}
