//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.Infrastructure;


namespace Integration.InfrastructureServiceAsync
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure-service-async/", ConfigurationName="InfrastructurePortsTypeAsync")]
    public interface InfrastructurePortsTypeAsync
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией importOKI не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importOKI", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importOKI", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfrastructureType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResourceType))]
        importOKIResponseMessage importOKI(importOKIRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией exportOKI не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportOKI", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportOKI", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfrastructureType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResourceType))]
        exportOKIResponseMessage exportOKI(exportOKIRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getState", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:getState", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(InfrastructureType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResourceType))]
        getStateResponseMessage getState(getStateRequestMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importOKIRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importOKIRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/", Order=0)]
        public importOKIRequest importOKIRequest1;
        
        public importOKIRequestMessage()
        {
        }
        
        public importOKIRequestMessage(RequestHeader RequestHeader, importOKIRequest importOKIRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importOKIRequest1 = importOKIRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importOKIResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public importOKIResponseMessage()
        {
        }
        
        public importOKIResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportOKIRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exportOKIRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/", Order=0)]
        public exportOKIRequest exportOKIRequest1;
        
        public exportOKIRequestMessage()
        {
        }
        
        public exportOKIRequestMessage(RequestHeader RequestHeader, exportOKIRequest exportOKIRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.exportOKIRequest1 = exportOKIRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportOKIResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public exportOKIResponseMessage()
        {
        }
        
        public exportOKIResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStateRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public getStateRequest getStateRequest1;
        
        public getStateRequestMessage()
        {
        }
        
        public getStateRequestMessage(RequestHeader RequestHeader, getStateRequest getStateRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.getStateRequest1 = getStateRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/infrastructure/", Order=0)]
        public getStateResult getStateResult;
        
        public getStateResponseMessage()
        {
        }
        
        public getStateResponseMessage(ResultHeader ResultHeader, getStateResult getStateResult)
        {
            this.ResultHeader = ResultHeader;
            this.getStateResult = getStateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InfrastructurePortsTypeAsyncChannel : InfrastructurePortsTypeAsync, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public class InfrastructurePortsTypeAsyncClient : System.ServiceModel.ClientBase<InfrastructurePortsTypeAsync>, InfrastructurePortsTypeAsync
    {
        
        public InfrastructurePortsTypeAsyncClient()
        {
        }
        
        public InfrastructurePortsTypeAsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public InfrastructurePortsTypeAsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public InfrastructurePortsTypeAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public InfrastructurePortsTypeAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importOKIResponseMessage InfrastructurePortsTypeAsync.importOKI(importOKIRequestMessage request)
        {
            return base.Channel.importOKI(request);
        }
        
        public ResultHeader importOKI(RequestHeader RequestHeader, importOKIRequest importOKIRequest1, out AckRequest AckRequest)
        {
            importOKIRequestMessage inValue = new importOKIRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importOKIRequest1 = importOKIRequest1;
            importOKIResponseMessage retVal = ((InfrastructurePortsTypeAsync)(this)).importOKI(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        exportOKIResponseMessage InfrastructurePortsTypeAsync.exportOKI(exportOKIRequestMessage request)
        {
            return base.Channel.exportOKI(request);
        }
        
        public ResultHeader exportOKI(RequestHeader RequestHeader, exportOKIRequest exportOKIRequest1, out AckRequest AckRequest)
        {
            exportOKIRequestMessage inValue = new exportOKIRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.exportOKIRequest1 = exportOKIRequest1;
            exportOKIResponseMessage retVal = ((InfrastructurePortsTypeAsync)(this)).exportOKI(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getStateResponseMessage InfrastructurePortsTypeAsync.getState(getStateRequestMessage request)
        {
            return base.Channel.getState(request);
        }
        
        public ResultHeader getState(RequestHeader RequestHeader, getStateRequest getStateRequest1, out getStateResult getStateResult)
        {
            getStateRequestMessage inValue = new getStateRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.getStateRequest1 = getStateRequest1;
            getStateResponseMessage retVal = ((InfrastructurePortsTypeAsync)(this)).getState(inValue);
            getStateResult = retVal.getStateResult;
            return retVal.ResultHeader;
        }
    }
}
