//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.NsiBase;


namespace Integration.NsiCommon
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class exportNsiListRequest : BaseType
    {
        
        public exportNsiListRequest()
        {
            this.version = "10.0.1.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-base/", Order=0)]
        public ListGroup ListGroup { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class exportNsiItemRequest : BaseType
    {
        
        public exportNsiItemRequest()
        {
            this.version = "10.0.1.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string RegistryNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-base/", Order=1)]
        public ListGroup ListGroup { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime ModifiedAfter { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class exportNsiPagingItemRequest : BaseType
    {
        
        public exportNsiPagingItemRequest()
        {
            this.version = "10.0.1.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger", Order=0)]
        public string RegistryNumber { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-base/", Order=1)]
        public ListGroup ListGroup { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Page { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime ModifiedAfter { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class getStateResult : BaseAsyncResponseType
    {
        
        public getStateResult()
        {
            this.version = "10.0.1.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NsiItem", typeof(NsiItemType), Order=1)]
        public NsiItemType NsiItem { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NsiList", typeof(NsiListType), Order=2)]
        public NsiListType NsiList { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NsiPagingItem", typeof(getStateResultNsiPagingItem), Order=3)]
        public getStateResultNsiPagingItem NsiPagingItem { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class getStateResultNsiPagingItem : NsiItemType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalItemsCount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalPages { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object CurrentPage { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class exportNsiListResult : BaseType
    {
        
        public exportNsiListResult()
        {
            this.version = "10.0.1.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NsiList", typeof(NsiListType), Order=1)]
        public NsiListType NsiList { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class exportNsiItemResult : BaseType
    {
        
        public exportNsiItemResult()
        {
            this.version = "10.0.1.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NsiItem", typeof(NsiItemType), Order=1)]
        public NsiItemType NsiItem { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class exportNsiPagingItemResult : BaseType
    {
        
        public exportNsiPagingItemResult()
        {
            this.version = "10.0.1.2";
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ErrorMessage", typeof(ErrorMessageType), Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public ErrorMessageType ErrorMessage { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("NsiItem", typeof(exportNsiPagingItemResultNsiItem), Order=1)]
        public exportNsiPagingItemResultNsiItem NsiItem { get; set; }
        
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public string version { get; set; }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Svc2CodeConverter", "1.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/")]
    public class exportNsiPagingItemResultNsiItem : NsiItemType
    {
        
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int TotalItemsCount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int TotalPages { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object CurrentPage { get; set; }
    }
}
