//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.NsiCommon;
using Integration.Xmldsig;


namespace Integration.NsiCommonServiceAsync
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common-service-async/", ConfigurationName="NsiPortsTypeAsync")]
    public interface NsiPortsTypeAsync
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией exportNsiList не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportNsiList", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportNsiList", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        exportNsiListResponseMessage exportNsiList(exportNsiListRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией exportNsiItem не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportNsiItem", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportNsiItem", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        exportNsiItemResponseMessage exportNsiItem(exportNsiItemRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией exportNsiPagingItem не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportNsiPagingItem", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportNsiPagingItem", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        exportNsiPagingItemResponseMessage exportNsiPagingItem(exportNsiPagingItemRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getState", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:getState", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(CommonResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(DocumentPortalType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ManifestType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(OKTMORefType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RegionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResultType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SignaturePropertiesType))]
        getStateResponseMessage getState(getStateRequestMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportNsiListRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public HeaderType ISRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exportNsiListRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/", Order=0)]
        public exportNsiListRequest exportNsiListRequest1;
        
        public exportNsiListRequestMessage()
        {
        }
        
        public exportNsiListRequestMessage(HeaderType ISRequestHeader, exportNsiListRequest exportNsiListRequest1)
        {
            this.ISRequestHeader = ISRequestHeader;
            this.exportNsiListRequest1 = exportNsiListRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportNsiListResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public exportNsiListResponseMessage()
        {
        }
        
        public exportNsiListResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportNsiItemRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public HeaderType ISRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exportNsiItemRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/", Order=0)]
        public exportNsiItemRequest exportNsiItemRequest1;
        
        public exportNsiItemRequestMessage()
        {
        }
        
        public exportNsiItemRequestMessage(HeaderType ISRequestHeader, exportNsiItemRequest exportNsiItemRequest1)
        {
            this.ISRequestHeader = ISRequestHeader;
            this.exportNsiItemRequest1 = exportNsiItemRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportNsiItemResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public exportNsiItemResponseMessage()
        {
        }
        
        public exportNsiItemResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportNsiPagingItemRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public HeaderType ISRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exportNsiPagingItemRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/", Order=0)]
        public exportNsiPagingItemRequest exportNsiPagingItemRequest1;
        
        public exportNsiPagingItemRequestMessage()
        {
        }
        
        public exportNsiPagingItemRequestMessage(HeaderType ISRequestHeader, exportNsiPagingItemRequest exportNsiPagingItemRequest1)
        {
            this.ISRequestHeader = ISRequestHeader;
            this.exportNsiPagingItemRequest1 = exportNsiPagingItemRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportNsiPagingItemResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public exportNsiPagingItemResponseMessage()
        {
        }
        
        public exportNsiPagingItemResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public HeaderType ISRequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStateRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public getStateRequest getStateRequest1;
        
        public getStateRequestMessage()
        {
        }
        
        public getStateRequestMessage(HeaderType ISRequestHeader, getStateRequest getStateRequest1)
        {
            this.ISRequestHeader = ISRequestHeader;
            this.getStateRequest1 = getStateRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/nsi-common/", Order=0)]
        public getStateResult getStateResult;
        
        public getStateResponseMessage()
        {
        }
        
        public getStateResponseMessage(ResultHeader ResultHeader, getStateResult getStateResult)
        {
            this.ResultHeader = ResultHeader;
            this.getStateResult = getStateResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NsiPortsTypeAsyncChannel : NsiPortsTypeAsync, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public class NsiCommonPortsTypeAsyncClient : System.ServiceModel.ClientBase<NsiPortsTypeAsync>, NsiPortsTypeAsync
    {
        
        public NsiCommonPortsTypeAsyncClient()
        {
        }
        
        public NsiCommonPortsTypeAsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public NsiCommonPortsTypeAsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NsiCommonPortsTypeAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public NsiCommonPortsTypeAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        exportNsiListResponseMessage NsiPortsTypeAsync.exportNsiList(exportNsiListRequestMessage request)
        {
            return base.Channel.exportNsiList(request);
        }
        
        public ResultHeader exportNsiList(HeaderType ISRequestHeader, exportNsiListRequest exportNsiListRequest1, out AckRequest AckRequest)
        {
            exportNsiListRequestMessage inValue = new exportNsiListRequestMessage();
            inValue.ISRequestHeader = ISRequestHeader;
            inValue.exportNsiListRequest1 = exportNsiListRequest1;
            exportNsiListResponseMessage retVal = ((NsiPortsTypeAsync)(this)).exportNsiList(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        exportNsiItemResponseMessage NsiPortsTypeAsync.exportNsiItem(exportNsiItemRequestMessage request)
        {
            return base.Channel.exportNsiItem(request);
        }
        
        public ResultHeader exportNsiItem(HeaderType ISRequestHeader, exportNsiItemRequest exportNsiItemRequest1, out AckRequest AckRequest)
        {
            exportNsiItemRequestMessage inValue = new exportNsiItemRequestMessage();
            inValue.ISRequestHeader = ISRequestHeader;
            inValue.exportNsiItemRequest1 = exportNsiItemRequest1;
            exportNsiItemResponseMessage retVal = ((NsiPortsTypeAsync)(this)).exportNsiItem(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        exportNsiPagingItemResponseMessage NsiPortsTypeAsync.exportNsiPagingItem(exportNsiPagingItemRequestMessage request)
        {
            return base.Channel.exportNsiPagingItem(request);
        }
        
        public ResultHeader exportNsiPagingItem(HeaderType ISRequestHeader, exportNsiPagingItemRequest exportNsiPagingItemRequest1, out AckRequest AckRequest)
        {
            exportNsiPagingItemRequestMessage inValue = new exportNsiPagingItemRequestMessage();
            inValue.ISRequestHeader = ISRequestHeader;
            inValue.exportNsiPagingItemRequest1 = exportNsiPagingItemRequest1;
            exportNsiPagingItemResponseMessage retVal = ((NsiPortsTypeAsync)(this)).exportNsiPagingItem(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getStateResponseMessage NsiPortsTypeAsync.getState(getStateRequestMessage request)
        {
            return base.Channel.getState(request);
        }
        
        public ResultHeader getState(HeaderType ISRequestHeader, getStateRequest getStateRequest1, out getStateResult getStateResult)
        {
            getStateRequestMessage inValue = new getStateRequestMessage();
            inValue.ISRequestHeader = ISRequestHeader;
            inValue.getStateRequest1 = getStateRequest1;
            getStateResponseMessage retVal = ((NsiPortsTypeAsync)(this)).getState(inValue);
            getStateResult = retVal.getStateResult;
            return retVal.ResultHeader;
        }
    }
}
