//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

using Integration.Base;
using Integration.Payment;
using Integration.PaymentsBase;


namespace Integration.PaymentServiceAsync
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/payment-service-async/", ConfigurationName="PaymentPortsTypeAsync")]
    public interface PaymentPortsTypeAsync
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией importNotificationsOfOrderExecution не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importNotificationsOfOrderExecution", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importNotificationsOfOrderExecution", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NotificationOfOrderExecutionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SupplierNotificationOfOrderExecutionType))]
        importNotificationsOfOrderExecutionResponseMessage importNotificationsOfOrderExecution(importNotificationsOfOrderExecutionRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией importNotificationsOfOrderExecutionCancellation не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importNotificationsOfOrderExecutionCancellation", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importNotificationsOfOrderExecutionCancellation", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NotificationOfOrderExecutionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SupplierNotificationOfOrderExecutionType))]
        importNotificationsOfOrderExecutionResponseMessage importNotificationsOfOrderExecutionCancellation(importNotificationsOfOrderExecutionCancellationRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getState", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:getState", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NotificationOfOrderExecutionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SupplierNotificationOfOrderExecutionType))]
        getStateResponseMessage getState(getStateRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией exportPaymentDocumentDetails не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:exportPaymentDocumentDetails", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:exportPaymentDocumentDetails", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NotificationOfOrderExecutionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SupplierNotificationOfOrderExecutionType))]
        importNotificationsOfOrderExecutionResponseMessage exportPaymentDocumentDetails(exportPaymentDocumentDetailsRequestMessage request);
        
        // CODEGEN: Контракт генерации сообщений с операцией importSupplierNotificationsOfOrderExecution не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:importSupplierNotificationsOfOrderExecution", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Fault), Action="urn:importSupplierNotificationsOfOrderExecution", Name="Fault", Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(BaseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(HeaderType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(NotificationOfOrderExecutionType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(SupplierNotificationOfOrderExecutionType))]
        importNotificationsOfOrderExecutionResponseMessage importSupplierNotificationsOfOrderExecution(importSupplierNotificationsOfOrderExecutionRequestMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importNotificationsOfOrderExecutionRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importNotificationsOfOrderExecutionRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/payment/", Order=0)]
        public importNotificationsOfOrderExecutionRequest importNotificationsOfOrderExecutionRequest1;
        
        public importNotificationsOfOrderExecutionRequestMessage()
        {
        }
        
        public importNotificationsOfOrderExecutionRequestMessage(RequestHeader RequestHeader, importNotificationsOfOrderExecutionRequest importNotificationsOfOrderExecutionRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importNotificationsOfOrderExecutionRequest1 = importNotificationsOfOrderExecutionRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importNotificationsOfOrderExecutionResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public AckRequest AckRequest;
        
        public importNotificationsOfOrderExecutionResponseMessage()
        {
        }
        
        public importNotificationsOfOrderExecutionResponseMessage(ResultHeader ResultHeader, AckRequest AckRequest)
        {
            this.ResultHeader = ResultHeader;
            this.AckRequest = AckRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importNotificationsOfOrderExecutionCancellationRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importNotificationsOfOrderExecutionCancellationRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/payment/", Order=0)]
        public importNotificationsOfOrderExecutionCancellationRequest importNotificationsOfOrderExecutionCancellationRequest1;
        
        public importNotificationsOfOrderExecutionCancellationRequestMessage()
        {
        }
        
        public importNotificationsOfOrderExecutionCancellationRequestMessage(RequestHeader RequestHeader, importNotificationsOfOrderExecutionCancellationRequest importNotificationsOfOrderExecutionCancellationRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importNotificationsOfOrderExecutionCancellationRequest1 = importNotificationsOfOrderExecutionCancellationRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getStateRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/base/", Order=0)]
        public getStateRequest getStateRequest1;
        
        public getStateRequestMessage()
        {
        }
        
        public getStateRequestMessage(RequestHeader RequestHeader, getStateRequest getStateRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.getStateRequest1 = getStateRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class getStateResponseMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public ResultHeader ResultHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/payment/", Order=0)]
        public getStateResult getStateResult;
        
        public getStateResponseMessage()
        {
        }
        
        public getStateResponseMessage(ResultHeader ResultHeader, getStateResult getStateResult)
        {
            this.ResultHeader = ResultHeader;
            this.getStateResult = getStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class exportPaymentDocumentDetailsRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="exportPaymentDocumentDetailsRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/payment/", Order=0)]
        public exportPaymentDocumentDetailsRequest exportPaymentDocumentDetailsRequest1;
        
        public exportPaymentDocumentDetailsRequestMessage()
        {
        }
        
        public exportPaymentDocumentDetailsRequestMessage(RequestHeader RequestHeader, exportPaymentDocumentDetailsRequest exportPaymentDocumentDetailsRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.exportPaymentDocumentDetailsRequest1 = exportPaymentDocumentDetailsRequest1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public class importSupplierNotificationsOfOrderExecutionRequestMessage
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://dom.gosuslugi.ru/schema/integration/base/")]
        public RequestHeader RequestHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="importSupplierNotificationsOfOrderExecutionRequest", Namespace="http://dom.gosuslugi.ru/schema/integration/payment/", Order=0)]
        public importSupplierNotificationsOfOrderExecutionRequest importSupplierNotificationsOfOrderExecutionRequest1;
        
        public importSupplierNotificationsOfOrderExecutionRequestMessage()
        {
        }
        
        public importSupplierNotificationsOfOrderExecutionRequestMessage(RequestHeader RequestHeader, importSupplierNotificationsOfOrderExecutionRequest importSupplierNotificationsOfOrderExecutionRequest1)
        {
            this.RequestHeader = RequestHeader;
            this.importSupplierNotificationsOfOrderExecutionRequest1 = importSupplierNotificationsOfOrderExecutionRequest1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PaymentPortsTypeAsyncChannel : PaymentPortsTypeAsync, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public class PaymentPortsTypeAsyncClient : System.ServiceModel.ClientBase<PaymentPortsTypeAsync>, PaymentPortsTypeAsync
    {
        
        public PaymentPortsTypeAsyncClient()
        {
        }
        
        public PaymentPortsTypeAsyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public PaymentPortsTypeAsyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PaymentPortsTypeAsyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public PaymentPortsTypeAsyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importNotificationsOfOrderExecutionResponseMessage PaymentPortsTypeAsync.importNotificationsOfOrderExecution(importNotificationsOfOrderExecutionRequestMessage request)
        {
            return base.Channel.importNotificationsOfOrderExecution(request);
        }
        
        public ResultHeader importNotificationsOfOrderExecution(RequestHeader RequestHeader, importNotificationsOfOrderExecutionRequest importNotificationsOfOrderExecutionRequest1, out AckRequest AckRequest)
        {
            importNotificationsOfOrderExecutionRequestMessage inValue = new importNotificationsOfOrderExecutionRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importNotificationsOfOrderExecutionRequest1 = importNotificationsOfOrderExecutionRequest1;
            importNotificationsOfOrderExecutionResponseMessage retVal = ((PaymentPortsTypeAsync)(this)).importNotificationsOfOrderExecution(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importNotificationsOfOrderExecutionResponseMessage PaymentPortsTypeAsync.importNotificationsOfOrderExecutionCancellation(importNotificationsOfOrderExecutionCancellationRequestMessage request)
        {
            return base.Channel.importNotificationsOfOrderExecutionCancellation(request);
        }
        
        public ResultHeader importNotificationsOfOrderExecutionCancellation(RequestHeader RequestHeader, importNotificationsOfOrderExecutionCancellationRequest importNotificationsOfOrderExecutionCancellationRequest1, out AckRequest AckRequest)
        {
            importNotificationsOfOrderExecutionCancellationRequestMessage inValue = new importNotificationsOfOrderExecutionCancellationRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importNotificationsOfOrderExecutionCancellationRequest1 = importNotificationsOfOrderExecutionCancellationRequest1;
            importNotificationsOfOrderExecutionResponseMessage retVal = ((PaymentPortsTypeAsync)(this)).importNotificationsOfOrderExecutionCancellation(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        getStateResponseMessage PaymentPortsTypeAsync.getState(getStateRequestMessage request)
        {
            return base.Channel.getState(request);
        }
        
        public ResultHeader getState(RequestHeader RequestHeader, getStateRequest getStateRequest1, out getStateResult getStateResult)
        {
            getStateRequestMessage inValue = new getStateRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.getStateRequest1 = getStateRequest1;
            getStateResponseMessage retVal = ((PaymentPortsTypeAsync)(this)).getState(inValue);
            getStateResult = retVal.getStateResult;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importNotificationsOfOrderExecutionResponseMessage PaymentPortsTypeAsync.exportPaymentDocumentDetails(exportPaymentDocumentDetailsRequestMessage request)
        {
            return base.Channel.exportPaymentDocumentDetails(request);
        }
        
        public ResultHeader exportPaymentDocumentDetails(RequestHeader RequestHeader, exportPaymentDocumentDetailsRequest exportPaymentDocumentDetailsRequest1, out AckRequest AckRequest)
        {
            exportPaymentDocumentDetailsRequestMessage inValue = new exportPaymentDocumentDetailsRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.exportPaymentDocumentDetailsRequest1 = exportPaymentDocumentDetailsRequest1;
            importNotificationsOfOrderExecutionResponseMessage retVal = ((PaymentPortsTypeAsync)(this)).exportPaymentDocumentDetails(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        importNotificationsOfOrderExecutionResponseMessage PaymentPortsTypeAsync.importSupplierNotificationsOfOrderExecution(importSupplierNotificationsOfOrderExecutionRequestMessage request)
        {
            return base.Channel.importSupplierNotificationsOfOrderExecution(request);
        }
        
        public ResultHeader importSupplierNotificationsOfOrderExecution(RequestHeader RequestHeader, importSupplierNotificationsOfOrderExecutionRequest importSupplierNotificationsOfOrderExecutionRequest1, out AckRequest AckRequest)
        {
            importSupplierNotificationsOfOrderExecutionRequestMessage inValue = new importSupplierNotificationsOfOrderExecutionRequestMessage();
            inValue.RequestHeader = RequestHeader;
            inValue.importSupplierNotificationsOfOrderExecutionRequest1 = importSupplierNotificationsOfOrderExecutionRequest1;
            importNotificationsOfOrderExecutionResponseMessage retVal = ((PaymentPortsTypeAsync)(this)).importSupplierNotificationsOfOrderExecution(inValue);
            AckRequest = retVal.AckRequest;
            return retVal.ResultHeader;
        }
    }
}
